### PR TITLE
Remove unused dependency react-email

### PR DESCRIPTION
**Pull request by jirutka**
## Description

This package is not imported anywhere and has a lot of transitional runtime dependencies. Some of these are clearly build/development dependencies (e.g. swc, webpack) and they are even propagated into NextJS standalone builds, making it much bigger than it needs to be.

Note that there're also @react-email/components and @react-email/render - unlike "react-email", these dependencies are used.

## Checklist

Please check off all the following items with an "x" in the boxes before requesting a review.

- [x] I have performed a self-review of my code
- [x] My code follows the code style of this project
- [x] I have commented my code, particularly in hard-to-understand areas

## Summary by CodeRabbit

- **Chores**
  - Removed unused dependency `"react-email": "^2.0.0"` from the email package.

### CODE REVIEW

**Comment by lukevella** [comment]
The `react-email` package is used to be able to [launch a dev server](https://github.com/lukevella/rallly/blob/main/packages/emails/package.json#L6) (amongst other things) that allow us to preview our email templates during development.

**Comment by jirutka** [comment]
Isn't this provided by `preview-email`? Anyway, then it should be in `devDependencies`, not `dependencies`.

**Comment by lukevella** [comment]
> Isn't this provided by preview-email? 

`preview-email` serves a different purpose. It opens the an email in the browser during development. Useful for things like getting a verification code but it's not for building email templates.

> Anyway, then it should be in devDependencies, not dependencies

Maybe, but the [react-email](https://react.email/docs/getting-started/manual-setup) docs suggest otherwise.

**Comment by jirutka** [comment]
> Maybe, but the [react-email](https://react.email/docs/getting-started/manual-setup) docs suggest otherwise.

Well, the author of react-email either doesn’t know or doesn’t care about the difference between runtime and build-time/dev dependencies. :shrug: 

* https://www.geeksforgeeks.org/difference-between-dependencies-devdependencies-and-peerdependencies/
* https://frontendinterviewquestions.medium.com/difference-between-dependency-and-devdependency-2e8812b3f838

> To summarize, `dependencies` includes packages needed for the application to run in a production environment, while `devDependencies` includes packages required during development and testing but are not necessary for the production deployment.

**Pull request closed without merging**
