### PR TITLE
Docker compose - local development fixes

### PR DESCRIPTION
**Pull request by tommilligan**
I'm interested in the project, and thinking of taking on one of the open issues. I ran into a few issues getting local development with `docker-compose` set up - this PR suggests some fixes:

- incompatible with `mongo:latest`
  - changed docker compose to use `mongo:3.4`
- `npm install -q` fails to install `bower` modules.
  - use `yarn` and and copy bower config files to the build container
- cannot debug sent emails
  - added a `mail` service based on `maildev`. This lightweight container allows UI debugging of emails during development
- always regenerate configuration when running `Dockerfile`

Feedback welcome, as well as any thoughts you have on the project roadmap?

### CODE REVIEW

**Comment by tommilligan** [comment]
@lukevella is this something you're still interested in?

**Comment by Avalarion** [comment]
Hey Tom,

if @lukevella is not responding, would you create a fork? There are a lot of features that I would love to see, but I am not able to write NodeJS =/.

This here is more or less one...

Have a nice weekend,

Bastian

**Comment by tommilligan** [comment]
Thanks @Avalarion, I might do if I have time. Fraid' I can't promise anything at the moment though.

If you have some thoughts on features you'd like to try and implement yourself, I'm happy to get you started on the right track/give you some pointers etc.

**Comment by tommilligan** [comment]
Closing this as the project looks dead (16 months with no reply from maintainer, 8 months since last commit).

**Pull request closed without merging**
