### PR TITLE
Issue #570: Add heartbeat tests

### PR DESCRIPTION
**Pull request by rjtrenchard**
## Description

Adds a heartbeat-test in the /apps directory that can be used to check the health of prod.
This can be set up in Actions to check hourly, as per the issue tickets instructions.

An example workflow file has been provided, as well as some sample tests.

Feedback appreciated!

## Checklist

Please check off all the following items with an "x" in the boxes before requesting a review.

- [x] I have performed a self-review of my code
- [x] My code follows the code style of this project
- [x] I have commented my code, particularly in hard-to-understand areas

## Summary by CodeRabbit

- **New Features**
  - Added a README file for the heartbeat-test app with installation, configuration, and usage guidelines.
  - Introduced a sample workflow file for conducting heartbeat tests, including CI steps and failure reporting.
  - Implemented a Playwright configuration script for the heartbeat-test application.
  - Added Playwright end-to-end tests for Rallly, including tests for accessing specific paths and verifying page titles.

### CODE REVIEW

**Comment by lukevella** [comment]
Hi @rjtrenchard, thanks for working on this. I'm focusing on other tasks at the moment but I will review this asap.

**Comment by rjtrenchard** [comment]
> Hi @rjtrenchard, thanks for working on this. I'm focusing on other tasks at the moment but I will review this asap.

That's good to hear! Me and my team hope we understood the issue correctly. If we haven't, we will amend it.

**Comment by lukevella** [comment]
Sorry to keep you waiting @rjtrenchard. Truth is, this is a back-burner issue so it's hard to justify spending time on this as I need to focus on other tasks. I'll keep this open for now as I hope to come back to it when I have time.

**Comment by LeviAdamMiller** [comment]
Hi @lukevella, any chance you could take some time to look into our team's pull request.

**Comment by lukevella** [comment]
First, thank you for taking the time to set this up. Having spent some time looking into this it seems that it is [recommended](https://github.com/vercel/turborepo/discussions/2320) to keep tests within the package they are testing so I won't be proceeding with this approach.

**Pull request closed without merging**
