### PR TITLE
add german locales

### PR DESCRIPTION
**Pull request by anbucher**
Hi, I translated the locales to german. Would be happy to see them in Rallly.

### CODE REVIEW

**Comment by lukevella** [comment]
Hi @anbucher, thanks for taking the time to do these translations. There's still some steps I need to do to actually be able to make use of these and there are more translation keys that need to be added to make a complete translation. I'll keep this open for now and circle back to it once these are done. Thanks again.

**Comment by amandasystems** [comment]
I can do Swedish translations when that's possible, following for updates on that!

**Comment by lukevella** [comment]
Closing this as translations will most likely be handled through a third party service. I'll post an update once this is available.

**Comment by lukevella** [comment]
Hi @anbucher, if you're still interested in translating the app in German please have a look at this guide:  https://github.com/lukevella/rallly/wiki/Guide-for-translators

Thanks :)

**Pull request closed without merging**
